---
- name: Restart Windows Server
  hosts: windows_servers
  tasks:
    - name: Reboot the Windows server
      ansible.windows.win_reboot:
        reboot_timeout: 600  # waktu tunggu dalam detik
