- name: Playbook untuk menjalankan PowerShell dan restart server Windows
  hosts: windows_servers
  gather_facts: no
  tasks:
    - name: Restart Windows Server
      win_reboot:
        reboot_timeout_sec: 600
        msg: "Server akan direstart oleh Ansible playbook"
